"""Compatibility facade for the package-owned path implementation."""

from petpet.app.paths import (
    ANIMATIONS_DIR,
    APP_NAME,
    ASSET_ROOT_DIR,
    ASSETS_DIR,
    DATA_DIR,
    DATA_FILENAMES,
    DECORATIONS_DIR,
    DESKTOP_PET_DIR,
    FURNITURE_DIR,
    HOME_FURNITURE_DIR,
    HOME_PET_DIR,
    HOME_POSES_DIR,
    HOME_SCENES_DIR,
    ICONS_DIR,
    IS_FROZEN,
    LEGACY_UPDATE_DIR_NAMES,
    MAC_BUNDLE_ID,
    KNOWLEDGE_DIR,
    POSES_DIR,
    PROPS_DIR,
    RESOURCE_DIR,
    SCENES_DIR,
    SOUNDS_DIR,
    SOURCE_DIR,
    SOURCE_ASSETS_DIR,
    _copy_missing_data_files,
    _legacy_windows_data_dirs,
    _migrate_legacy_source_data,
    _seed_default_config,
    _windows_app_data_dir,
)


__all__ = (
    "ANIMATIONS_DIR",
    "APP_NAME",
    "ASSET_ROOT_DIR",
    "ASSETS_DIR",
    "DATA_DIR",
    "DATA_FILENAMES",
    "DECORATIONS_DIR",
    "DESKTOP_PET_DIR",
    "FURNITURE_DIR",
    "HOME_FURNITURE_DIR",
    "HOME_PET_DIR",
    "HOME_POSES_DIR",
    "HOME_SCENES_DIR",
    "ICONS_DIR",
    "IS_FROZEN",
    "LEGACY_UPDATE_DIR_NAMES",
    "MAC_BUNDLE_ID",
    "KNOWLEDGE_DIR",
    "POSES_DIR",
    "PROPS_DIR",
    "RESOURCE_DIR",
    "SCENES_DIR",
    "SOUNDS_DIR",
    "SOURCE_DIR",
    "SOURCE_ASSETS_DIR",
    "_copy_missing_data_files",
    "_legacy_windows_data_dirs",
    "_migrate_legacy_source_data",
    "_seed_default_config",
    "_windows_app_data_dir",
)
